# Generated by Django 5.0.4 on 2024-07-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playercard',
            unique_together=set(),
        ),
    ]
