# Generated by Django 5.0.4 on 2024-07-26 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_password',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'room')},
        ),
    ]
