# Generated by Django 5.0.4 on 2024-07-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_playercard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('0', 'Zero'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('D', 'Draw Two'), ('S', 'Skip'), ('R', 'Reverse'), ('W', 'Wild'), ('WD', 'Wild Draw Four'), ('G_W', 'Green Wild'), ('B_W', 'Blue Wild'), ('R_W', 'Red Wild'), ('Y_W', 'Yellow Wild'), ('G_WD', 'Green Wild Draw Four'), ('B_WD', 'Blue Wild Draw Four'), ('R_WD', 'Red Wild Draw Four'), ('Y_WD', 'Yellow Wild Draw Four')], max_length=4),
        ),
    ]
