# Generated by Django 5.0.4 on 2024-07-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('0', 'Zero'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('D', 'Draw Two'), ('S', 'Skip'), ('R', 'Reverse'), ('W', 'Wild'), ('WD', 'Wild Draw Four')], max_length=2),
        ),
    ]
