# Generated by Django 5.0.4 on 2024-07-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='chosen_suit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
