# Generated by Django 5.0.4 on 2024-07-26 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_player_unique_together_alter_player_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='last_played_card',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hand',
        ),
        migrations.RemoveField(
            model_name='player',
            name='room',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_full', models.BooleanField(default=False)),
                ('players', models.ManyToManyField(related_name='game_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
