# Generated by Django 5.0.4 on 2024-07-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameroom_chosen_suit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='uno_declared',
            field=models.BooleanField(default=False),
        ),
    ]
