# Generated by Django 5.0.4 on 2024-07-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_room_last_played_card_remove_player_hand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
