# Generated by Django 5.0.4 on 2024-07-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_gameroom_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue'), ('Y', 'Yellow'), ('S', 'Special')], max_length=1)),
                ('type', models.CharField(choices=[('0', 'Zero'), ('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('D', 'Draw Two'), ('S', 'Skip'), ('R', 'Reverse'), ('W', 'Wild'), ('WD', 'Wild Draw Four')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='gameroom',
            name='last_played_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.card'),
        ),
    ]
