# Generated by Django 5.0.4 on 2024-07-26 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_card_gameroom_last_played_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_cards', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_cards', to='game.gameroom')),
            ],
            options={
                'unique_together': {('player', 'card', 'room')},
            },
        ),
    ]
